apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-docker-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-docker-demo
  template:
    metadata:
      labels:
        app: k8s-docker-demo
    spec:
      containers:
      - name: k8s-docker-demo
        image: vinay1304/hello-k8s:latest
        ports:
        - containerPort: 80
